In [1]:
import pandas as pd

In [2]:
df_2025 = pd.read_excel("C:/Users/admin/Desktop/YRES/Andi Dong Submission -- Task 5/coaching_task_5/event-data-from-20250301-to-20251231.xlsx")
df_2026 = pd.read_csv("C:/Users/admin/Desktop/YRES/Andi Dong Submission -- Task 5/coaching_task_5/event-data-from-20260101-to-20260410.csv", dtype=str)

In [3]:
df_2025.head(10)

,Event Type Name,Start Date & Time,End Date & Time,Canceled By
0,ON: Volunteer Success Program,2025-03-11 16:45:00,2025-03-11 17:00:00,Host
1,ON: Volunteer Success Program,2025-03-03 15:00:00,2025-03-03 15:15:00,NaN
2,ON: Volunteer Success Program,2025-03-03 15:45:00,2025-03-03 16:00:00,NaN
3,ON: Volunteer Success Program,2025-03-06 16:15:00,2025-03-06 16:30:00,NaN
4,ON: Volunteer Success Program,2025-03-03 15:30:00,2025-03-03 15:45:00,NaN
5,ON: Volunteer Success Program,2025-03-04 15:30:00,2025-03-04 15:45:00,NaN
6,ON: Volunteer Success Program,2025-03-03 15:15:00,2025-03-03 15:30:00,NaN
7,ON: Volunteer Success Program,2025-03-04 15:45:00,2025-03-04 16:00:00,NaN
8,ON: Volunteer Success Program,2025-03-07 16:00:00,2025-03-07 16:15:00,Invitee
9,ON: Volunteer Success Program,2025-03-07 16:30:00,2025-03-07 16:45:00,Invitee

In [4]:
df_2025.tail(15)

,Event Type Name,Start Date & Time,End Date & Time,Canceled By
2145,ON: Volunteer Success Program,2026-01-08 15:00:00,2026-01-08 15:15:00,NaN
2146,ON: Volunteer Success Program,2026-01-08 16:00:00,2026-01-08 16:15:00,NaN
2147,BC/AB: Volunteer Success Program,2026-01-10 17:00:00,2026-01-10 17:15:00,Invitee
2148,BC/AB: Volunteer Success Program,2026-01-07 16:00:00,2026-01-07 16:15:00,NaN
2149,ON: Volunteer Success Program,2026-01-10 13:45:00,2026-01-10 14:00:00,NaN
2150,ON: Volunteer Success Program,2026-01-08 15:15:00,2026-01-08 15:30:00,NaN
2151,BC/AB: Volunteer Success Program,2026-01-05 17:00:00,2026-01-05 17:15:00,NaN
2152,BC/AB: Volunteer Success Program,2026-01-24 17:00:00,2026-01-24 17:15:00,NaN
2153,ON: Volunteer Success Program,2026-01-08 15:30:00,2026-01-08 15:45:00,NaN
2154,BC/AB: Volunteer Success Program,2026-01-05 17:30:00,2026-01-05 17:45:00,NaN
2155,BC/AB: Volunteer Success Program,2026-01-05 18:00:00,2026-01-05 18:15:00,NaN
2156,BC/AB: Volunteer Success Program,2026-01-07 18:30:00,2026-01-07 18:45:00,NaN
2157,ON: Volunteer Success Program,2026-01-08 15:45:00,2026-01-08 16:00:00,NaN
2158,BC/AB: Volunteer Success Program,2026-01-09 17:30:00,2026-01-09 17:45:00,NaN
2159,ON: Volunteer Success Program,2026-01-08 16:45:00,2026-01-08 17:00:00,NaN

In [5]:
df_2026.head(10)

,User Name,Team,Invitee Name,Invitee First Name,Invitee Last Name,Invitee Email,Invitee Time Zone,Invitee accepted marketing emails,Text Reminder Number,Event Type Name,...,Guest Email(s),Invitee Reconfirmed,Marked as No-Show,Meeting Notes,Group,User Email,Event UUID,Invitee UUID,Invitee scheduled by,Scheduling method
0,Volunteer YRES,NaN,Yash Kavale,Yash,Kavale,yashkavale60@gmail.com,Eastern Time - US & Canada,NaN,'+1 647-447-5460,ON: Volunteer Success Program,...,NaN,No,No,NaN,NaN,volunteer@yorkeducation.ca,ad6a9cd1-b41f-47db-ac9b-d54ff06bff4a,78729e31-83c6-48b6-a7fd-1a8405d333f6,NaN,NaN
1,Volunteer YRES,NaN,Mohit Sharma,Mohit,Sharma,mohitsharma1077@outlook.com,Eastern Time - US & Canada,NaN,'+1 416-276-4534,ON: Volunteer Success Program,...,NaN,Yes,No,NaN,NaN,volunteer@yorkeducation.ca,a8daae42-832a-4ab7-96fd-09a7c8f622ea,7becac09-8403-4210-972a-9045aadd5ff6,NaN,NaN
2,Volunteer YRES,NaN,Farsam,Farsam,NaN,farsam.shirazi@gmail.com,Eastern Time - US & Canada,NaN,NaN,ON: Volunteer Success Program,...,NaN,No,No,NaN,NaN,volunteer@yorkeducation.ca,bdddb559-2b29-49c6-afaf-7e70adafe525,2014f346-0211-496f-8f54-37af3543afa6,NaN,NaN
3,Volunteer YRES,NaN,Louise Bindon,Louise,Bindon,louisebindon@gmail.com,Pacific Time - US & Canada,NaN,NaN,BC/AB: Volunteer Success Program,...,NaN,NaN,No,NaN,NaN,volunteer@yorkeducation.ca,ec88b190-3565-4965-9f46-a8af593000d8,657178cf-e691-4c32-af1b-6f71b3eb07bf,NaN,NaN
4,Volunteer YRES,NaN,Jiayi Zhang,Jiayi,Zhang,zhangjiayi200110@hotmail.com,Pacific Time - US & Canada,NaN,NaN,BC/AB: Volunteer Success Program,...,NaN,NaN,No,NaN,NaN,volunteer@yorkeducation.ca,543adf9f-434f-4361-997a-8f153f9e23c3,df53d7f6-e828-4abe-b7f7-ccf2f8dd4206,NaN,NaN
5,Volunteer YRES,NaN,Daniel Wen,Daniel,Wen,daniel2009.wen@gmail.com,Eastern Time - US & Canada,NaN,'+1 647-459-9652,ON: Volunteer Success Program,...,NaN,Yes,No,NaN,NaN,volunteer@yorkeducation.ca,944e1266-e086-4b6e-81d3-75ff9189a5d1,fc320be3-f3b5-4358-b8ef-22fb62a52dfe,NaN,NaN
6,Volunteer YRES,NaN,Mohit Sharma,Mohit,Sharma,mohitsharma1077@outlook.com,Eastern Time - US & Canada,NaN,'+1 416-276-4534,ON: Volunteer Success Program,...,NaN,NaN,No,NaN,NaN,volunteer@yorkeducation.ca,24f6f9f7-efce-4242-b3d5-4c679ecfd545,d35c729c-ec26-402b-93c7-f664289d4a81,NaN,NaN
7,Volunteer YRES,NaN,Hazel Huang,Hazel,Huang,zige.huanghuang@gmail.com,Pacific Time - US & Canada,NaN,NaN,BC/AB: Volunteer Success Program,...,NaN,No,No,NaN,NaN,volunteer@yorkeducation.ca,07fec443-438f-4629-8f0f-2bc9687919f9,8ea9b0b1-fa20-434d-86f2-be0e7db347e5,NaN,NaN
8,Volunteer YRES,NaN,Louise Bindon,Louise,Bindon,louisebindon@gmail.com,Pacific Time - US & Canada,NaN,NaN,BC/AB: Volunteer Success Program,...,NaN,NaN,No,NaN,NaN,volunteer@yorkeducation.ca,99b473fd-72e1-4de7-91be-b62eb63fa424,2c85a320-2f3f-4f9f-9fb7-edc0b84c1e0e,NaN,NaN
9,Volunteer YRES,NaN,Audrey Anulegeh Wotazea,Audrey,Anulegeh Wotazea,aanulegeh@gmail.com,Eastern Time - US & Canada,NaN,'+1 416-908-9750,ON: Volunteer Success Program,...,NaN,Yes,No,NaN,NaN,volunteer@yorkeducation.ca,d407fc57-f5f5-4388-9b8d-987d00b485f5,72e22048-cdc0-49f3-8547-fed3c6a50acb,NaN,NaN

In [6]:
# 本周没有处理，需要额外操作
df_2026 = df_2026[['Event Type Name', 'Start Date & Time','End Date & Time','Canceled By']].copy()

In [7]:
df_2026.head(10)

,Event Type Name,Start Date & Time,End Date & Time,Canceled By
0,ON: Volunteer Success Program,2026-01-10 04:45 pm,2026-01-10 05:00 pm,Invitee
1,ON: Volunteer Success Program,2026-01-08 03:00 pm,2026-01-08 03:15 pm,NaN
2,ON: Volunteer Success Program,2026-01-08 04:00 pm,2026-01-08 04:15 pm,NaN
3,BC/AB: Volunteer Success Program,2026-01-10 05:00 pm,2026-01-10 05:15 pm,Invitee
4,BC/AB: Volunteer Success Program,2026-01-07 04:00 pm,2026-01-07 04:15 pm,Host
5,ON: Volunteer Success Program,2026-01-10 01:45 pm,2026-01-10 02:00 pm,NaN
6,ON: Volunteer Success Program,2026-01-08 03:15 pm,2026-01-08 03:30 pm,Host
7,BC/AB: Volunteer Success Program,2026-01-05 05:00 pm,2026-01-05 05:15 pm,NaN
8,BC/AB: Volunteer Success Program,2026-01-24 05:00 pm,2026-01-24 05:15 pm,Host
9,ON: Volunteer Success Program,2026-01-08 03:30 pm,2026-01-08 03:45 pm,NaN

In [8]:
print(df_2025.columns)

Index(['Event Type Name', 'Start Date & Time', 'End Date & Time',
       'Canceled By'],
      dtype='object')

In [9]:
print(df_2026.columns)

Index(['Event Type Name', 'Start Date & Time', 'End Date & Time',
       'Canceled By'],
      dtype='object')

In [10]:
df_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Event Type Name    2160 non-null   object
 1   Start Date & Time  2160 non-null   datetime64[ns]
 2   End Date & Time    2160 non-null   datetime64[ns]
 3   Canceled By        556 non-null    object
dtypes: datetime64[ns](2), object(2)
memory usage: 67.6+ KB

In [11]:
df_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Event Type Name    798 non-null    object
 1   Start Date & Time  798 non-null    object
 2   End Date & Time    798 non-null    object
 3   Canceled By        146 non-null    object
dtypes: object(4)
memory usage: 25.1+ KB

In [12]:
df_2025.isna().all(axis=1).sum()

np.int64(0)

In [13]:
df_2026.isna().all(axis=1).sum()

np.int64(0)

In [14]:
print(df_2025[['Event Type Name','Start Date & Time', 'End Date & Time']].isnull().any())

Event Type Name      False
Start Date & Time    False
End Date & Time      False
dtype: bool

In [15]:
print(df_2026[['Event Type Name','Start Date & Time', 'End Date & Time']].isnull().any())

Event Type Name      False
Start Date & Time    False
End Date & Time      False
dtype: bool

In [16]:
# Hence all those columns dont have any missing/NA value!

In [17]:
# check all the status
key_cols = ['Event Type Name', 'Start Date & Time', 'End Date & Time', 'Canceled By']

print(df_2025[key_cols].isna().sum())
print(df_2026[key_cols].isna().sum())

Event Type Name         0
Start Date & Time       0
End Date & Time         0
Canceled By          1604
dtype: int64
Event Type Name        0
Start Date & Time      0
End Date & Time        0
Canceled By          652
dtype: int64

In [18]:
df_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Event Type Name    2160 non-null   object
 1   Start Date & Time  2160 non-null   datetime64[ns]
 2   End Date & Time    2160 non-null   datetime64[ns]
 3   Canceled By        556 non-null    object
dtypes: datetime64[ns](2), object(2)
memory usage: 67.6+ KB

In [19]:
df_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Event Type Name    798 non-null    object
 1   Start Date & Time  798 non-null    object
 2   End Date & Time    798 non-null    object
 3   Canceled By        146 non-null    object
dtypes: object(4)
memory usage: 25.1+ KB

In [20]:
# 需要对2026年时间做转化！
df_2026['Start Date & Time'] = pd.to_datetime(df_2026['Start Date & Time'], errors = 'coerce')
df_2026['End Date & Time'] = pd.to_datetime(df_2026['End Date & Time'], errors = 'coerce')

C:\Users\admin\AppData\Local\Temp\ipykernel_14344\1112616388.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_2026['Start Date & Time'] = pd.to_datetime(df_2026['Start Date & Time'], errors = 'coerce')
C:\Users\admin\AppData\Local\Temp\ipykernel_14344\1112616388.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_2026['End Date & Time'] = pd.to_datetime(df_2026['End Date & Time'], errors = 'coerce')

In [21]:
df_2025.columns = df_2025.columns.str.strip().str.capitalize()
df_2026.columns = df_2026.columns.str.strip().str.capitalize()

In [22]:
df = pd.concat([df_2025, df_2026], ignore_index = True)

In [23]:
# 检查重复项并删除！
print(df_2025.duplicated().sum())
print(df_2026.duplicated().sum())
print(df.duplicated().sum())

26
10
48

In [24]:
df_cleaned = df.drop_duplicates().reset_index(drop=True)

In [26]:
print(len(df))
print(len(df_cleaned))
print(df_cleaned.isna().sum())

2958
2910
Event type name         0
Start date & time       0
End date & time         0
Canceled by          2245
dtype: int64

In [27]:
df_cleaned

,Event type name,Start date & time,End date & time,Canceled by
0,ON: Volunteer Success Program,2025-03-11 16:45:00,2025-03-11 17:00:00,Host
1,ON: Volunteer Success Program,2025-03-03 15:00:00,2025-03-03 15:15:00,NaN
2,ON: Volunteer Success Program,2025-03-03 15:45:00,2025-03-03 16:00:00,NaN
3,ON: Volunteer Success Program,2025-03-06 16:15:00,2025-03-06 16:30:00,NaN
4,ON: Volunteer Success Program,2025-03-03 15:30:00,2025-03-03 15:45:00,NaN
...,...,...,...,...
2905,ON: Volunteer Success Program,2026-04-12 12:30:00,2026-04-12 12:45:00,NaN
2906,ON: Volunteer Success Program,2026-04-17 16:00:00,2026-04-17 16:15:00,NaN
2907,ON: Volunteer Success Program,2026-04-13 13:45:00,2026-04-13 14:00:00,NaN
2908,ON: Volunteer Success Program,2026-04-14 16:45:00,2026-04-14 17:00:00,NaN
2909,ON: Volunteer Success Program,2026-04-10 15:00:00,2026-04-10 15:15:00,NaN

In [28]:
df_cleaned['Event type name'].unique()

array(['ON: Volunteer Success Program',
       'BC/AB: Volunteer Success Program'], dtype=object)

In [29]:
df_cleaned['Canceled by'].unique()

array(['Host', nan, 'Invitee'], dtype=object)

In [30]:
df_cleaned[['Province', 'Program name']] = df_cleaned['Event type name'].str.split(':', n = 1, expand = True)

In [31]:
df_cleaned['Province'] = df_cleaned['Province'].str.strip()
df_cleaned['Program name'] = df_cleaned['Program name'].str.strip()

In [33]:
# 一周代表从周日到周六
df_cleaned['Week Range'] = df_cleaned['Start date & time'].dt.to_period('W-SAT').apply(lambda r:f"{r.start_time.date()} to {r.end_time.date()}")

In [34]:
df_cleaned

,Event type name,Start date & time,End date & time,Canceled by,Province,Program name,Week Range
0,ON: Volunteer Success Program,2025-03-11 16:45:00,2025-03-11 17:00:00,Host,ON,Volunteer Success Program,2025-03-09 to 2025-03-15
1,ON: Volunteer Success Program,2025-03-03 15:00:00,2025-03-03 15:15:00,NaN,ON,Volunteer Success Program,2025-03-02 to 2025-03-08
2,ON: Volunteer Success Program,2025-03-03 15:45:00,2025-03-03 16:00:00,NaN,ON,Volunteer Success Program,2025-03-02 to 2025-03-08
3,ON: Volunteer Success Program,2025-03-06 16:15:00,2025-03-06 16:30:00,NaN,ON,Volunteer Success Program,2025-03-02 to 2025-03-08
4,ON: Volunteer Success Program,2025-03-03 15:30:00,2025-03-03 15:45:00,NaN,ON,Volunteer Success Program,2025-03-02 to 2025-03-08
...,...,...,...,...,...,...,...
2905,ON: Volunteer Success Program,2026-04-12 12:30:00,2026-04-12 12:45:00,NaN,ON,Volunteer Success Program,2026-04-12 to 2026-04-18
2906,ON: Volunteer Success Program,2026-04-17 16:00:00,2026-04-17 16:15:00,NaN,ON,Volunteer Success Program,2026-04-12 to 2026-04-18
2907,ON: Volunteer Success Program,2026-04-13 13:45:00,2026-04-13 14:00:00,NaN,ON,Volunteer Success Program,2026-04-12 to 2026-04-18
2908,ON: Volunteer Success Program,2026-04-14 16:45:00,2026-04-14 17:00:00,NaN,ON,Volunteer Success Program,2026-04-12 to 2026-04-18
2909,ON: Volunteer Success Program,2026-04-10 15:00:00,2026-04-10 15:15:00,NaN,ON,Volunteer Success Program,2026-04-05 to 2026-04-11

In [35]:
df_cleaned.to_csv("YRES_TASK_5_Coaching_report_cleaned_data.csv", index=False, encoding="utf-8")