In [1]:
# 检查数据集基本信息！

In [2]:
import pandas as pd
import numpy as np

In [3]:
vsp_raw = pd.read_excel("C:/Users/admin/Desktop/YRES/Andi Dong Submission -- Mar Report Advanced Task/March Volunteer Progress Report/VSP volunteers by Mar 31, 2026.xlsx")
interview_old_raw = pd.read_excel("C:/Users/admin/Desktop/YRES/Andi Dong Submission -- Mar Report Advanced Task/March Volunteer Progress Report/Calendly interviews records 20250301 to 20251231 (1).xlsx")
interview_new_raw = pd.read_excel("C:/Users/admin/Desktop/YRES/Andi Dong Submission -- Mar Report Advanced Task/March Volunteer Progress Report/Calendly interviews records 20260101 to 20260331.xlsx") 
activity_raw = pd.read_excel("C:/Users/admin/Desktop/YRES/Andi Dong Submission -- Mar Report Advanced Task/March Volunteer Progress Report/YRES Slack Member Analytics Mar 1- 31, 2026.xlsx")

In [4]:
vsp = vsp_raw.copy()
interview_old = interview_old_raw.copy()
interview_new = interview_new_raw.copy()
activity = activity_raw.copy()

In [5]:
# 对各个表格做简单分析和基本清洗！

### Q1 Among all VSP volunteers, who hasn’t booked an interview?

In [6]:
interview_old.shape

(2160, 9)

In [7]:
interview_new.shape

(739, 9)

In [8]:
vsp.shape

(2893, 10)

In [9]:
vsp.head()

,Name,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info
0,Mariam Ali,"U+ HR Account Sep 11, 2025 1:30 PM",mariam.ali@yorkeducation.ca,Yafet.Hailu@yorkeducation.ca,NaN,NaN,Bella He,Waiting To Be Placed,NaN,NaN
1,Manusha Srikanthan,"Jess Scott Sep 11, 2025 1:45 PM",manushasrikanthan@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN
2,Harvi Shah,"Jess Scott Sep 11, 2025 4:36 PM",harvishah2602@gmail.com,harvi.shah@yorkeducation.ca,Done,Interviewed,Tiffany Ye,In-training,Active,NaN
3,Dorsey Bangarh,"Jess Scott Sep 11, 2025 5:37 PM",dorseybangarh2004@gmail.com,dorsey.bangarh@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN
4,Pushti Ladani,"Jess Scott Sep 11, 2025 7:26 PM",pushti-kantilal.ladani@mohawkcollege.ca,pushti.ladani@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN

In [10]:
vsp.columns.tolist()

['Name',
 'Creation log',
 'Email Address',
 'YRES Email',
 'Contacted on Slack',
 'Interview Status',
 'Youth Advisor 3 - Winter 2026',
 'Placement Status',
 'Volunteer Status',
 'Share account info']

In [11]:
vsp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2893 entries, 0 to 2892
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Name                           2893 non-null   object
 1   Creation log                   2893 non-null   object
 2   Email Address                  2882 non-null   object
 3   YRES Email                     2279 non-null   object
 4   Contacted on Slack             943 non-null    object
 5   Interview Status               2091 non-null   object
 6   Youth Advisor 3 - Winter 2026  1883 non-null   object
 7   Placement Status               2893 non-null   object
 8   Volunteer Status               1370 non-null   object
 9   Share account info             985 non-null    object
dtypes: object(10)
memory usage: 226.1+ KB

In [12]:
interview_old.head()

,Invitee Name,Invitee First Name,Invitee Last Name,Invitee Email,Event Type Name,Start Date & Time,End Date & Time,Canceled,Canceled By
0,Baani Singh,Baani,Singh,baanii.singh@gmail.com,ON: Volunteer Success Program,2025-03-11 16:45:00,2025-03-11 17:00:00,True,Host
1,Alisa Khvostiuk,Alisa,Khvostiuk,alisa.khvostiuk@gmail.com,ON: Volunteer Success Program,2025-03-03 15:00:00,2025-03-03 15:15:00,False,NaN
2,Ryan Yang,Ryan,Yang,ryan.y2912@gmail.com,ON: Volunteer Success Program,2025-03-03 15:45:00,2025-03-03 16:00:00,False,NaN
3,Baani Singh,Baani,Singh,baanii.singh@gmail.com,ON: Volunteer Success Program,2025-03-06 16:15:00,2025-03-06 16:30:00,False,NaN
4,Mya Charlotte Wong,Mya,Charlotte Wong,vecchiamya@gmail.com,ON: Volunteer Success Program,2025-03-03 15:30:00,2025-03-03 15:45:00,False,NaN

In [13]:
interview_new.head()

,Invitee Name,Invitee First Name,Invitee Last Name,Invitee Email,Event Type Name,Start Date & Time,End Date & Time,Canceled,Canceled By
0,Yash Kavale,Yash,Kavale,yashkavale60@gmail.com,ON: Volunteer Success Program,2026-01-10 16:45:00,2026-01-10 17:00:00,True,Invitee
1,Mohit Sharma,Mohit,Sharma,mohitsharma1077@outlook.com,ON: Volunteer Success Program,2026-01-08 15:00:00,2026-01-08 15:15:00,False,NaN
2,Farsam,Farsam,NaN,farsam.shirazi@gmail.com,ON: Volunteer Success Program,2026-01-08 16:00:00,2026-01-08 16:15:00,False,NaN
3,Louise Bindon,Louise,Bindon,louisebindon@gmail.com,BC/AB: Volunteer Success Program,2026-01-10 17:00:00,2026-01-10 17:15:00,True,Invitee
4,Jiayi Zhang,Jiayi,Zhang,zhangjiayi200110@hotmail.com,BC/AB: Volunteer Success Program,2026-01-07 16:00:00,2026-01-07 16:15:00,True,Host

In [14]:
interview_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Invitee Name        2160 non-null   object
 1   Invitee First Name  2160 non-null   object
 2   Invitee Last Name   1871 non-null   object
 3   Invitee Email       2160 non-null   object
 4   Event Type Name     2160 non-null   object
 5   Start Date & Time   2160 non-null   datetime64[ns]
 6   End Date & Time     2160 non-null   datetime64[ns]
 7   Canceled            2160 non-null   bool
 8   Canceled By         556 non-null    object
dtypes: bool(1), datetime64[ns](2), object(6)
memory usage: 137.2+ KB

In [15]:
interview_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 739 entries, 0 to 738
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Invitee Name        739 non-null    object
 1   Invitee First Name  739 non-null    object
 2   Invitee Last Name   646 non-null    object
 3   Invitee Email       739 non-null    object
 4   Event Type Name     739 non-null    object
 5   Start Date & Time   739 non-null    datetime64[ns]
 6   End Date & Time     739 non-null    datetime64[ns]
 7   Canceled            739 non-null    bool
 8   Canceled By         135 non-null    object
dtypes: bool(1), datetime64[ns](2), object(6)
memory usage: 47.0+ KB

In [16]:
# Concatenation of two interview dataset!
interview_old['Invitee Name'] = interview_old['Invitee Name'].str.strip().str.title()
interview_new['Invitee Name'] = interview_new['Invitee Name'].str.strip().str.title()

In [17]:
interview_old[['Invitee Name', 'Start Date & Time', 'End Date & Time']].isnull().any(axis=1).sum()

np.int64(0)

In [18]:
interview_new[['Invitee Name', 'Start Date & Time', 'End Date & Time']].isnull().any(axis=1).sum()

np.int64(0)

In [19]:
interview_combined = pd.concat([interview_old, interview_new], ignore_index=True)

In [20]:
interview_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2899 entries, 0 to 2898
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Invitee Name        2899 non-null   object
 1   Invitee First Name  2899 non-null   object
 2   Invitee Last Name   2517 non-null   object
 3   Invitee Email       2899 non-null   object
 4   Event Type Name     2899 non-null   object
 5   Start Date & Time   2899 non-null   datetime64[ns]
 6   End Date & Time     2899 non-null   datetime64[ns]
 7   Canceled            2899 non-null   bool
 8   Canceled By         691 non-null    object
dtypes: bool(1), datetime64[ns](2), object(6)
memory usage: 184.1+ KB

In [21]:
# 筛选出重复的行（默认 keep='first'，即显示除第一条以外的重复项）
duplicate_rows = interview_combined[interview_combined.duplicated(subset=['Invitee Name', 'Start Date & Time', 'End Date & Time'], keep=False)]

# 按关键列排序，这样你可以直观地对比重复的项
duplicate_rows.sort_values(by=['Invitee Name', 'Start Date & Time'])

,Invitee Name,Invitee First Name,Invitee Last Name,Invitee Email,Event Type Name,Start Date & Time,End Date & Time,Canceled,Canceled By
1391,Adela Xu,Adela,Xu,xxiaotong.xu@outlook.com,BC/AB: Volunteer Success Program,2025-10-18 17:30:00,2025-10-18 17:45:00,True,Invitee
1525,Adela Xu,Adela,Xu,xxiaotong.xu@outlook.com,BC/AB: Volunteer Success Program,2025-10-18 17:30:00,2025-10-18 17:45:00,False,NaN
2159,Ana Alvarez,Ana,Alvarez,ana.alvarez.conforme@gmail.com,ON: Volunteer Success Program,2026-01-08 16:45:00,2026-01-08 17:00:00,False,NaN
2175,Ana Alvarez,Ana,Alvarez,ana.alvarez.conforme@gmail.com,ON: Volunteer Success Program,2026-01-08 16:45:00,2026-01-08 17:00:00,False,NaN
2154,Ana Paula Liendo Huapaya,Ana,Paula Liendo Huapaya,anapliendo@gmail.com,BC/AB: Volunteer Success Program,2026-01-05 17:30:00,2026-01-05 17:45:00,False,NaN
...,...,...,...,...,...,...,...,...,...
2160,Yash Kavale,Yash,Kavale,yashkavale60@gmail.com,ON: Volunteer Success Program,2026-01-10 16:45:00,2026-01-10 17:00:00,True,Invitee
2694,Zachary Ramos,Zachary,Ramos,zachmiguelle091008@gmail.com,ON: Volunteer Success Program,2026-03-10 16:15:00,2026-03-10 16:30:00,True,Invitee
2695,Zachary Ramos,Zachary,Ramos,zachmiguelle091008@gmail.com,ON: Volunteer Success Program,2026-03-10 16:15:00,2026-03-10 16:30:00,False,NaN
1327,Zachary Tseng,Zachary,Tseng,zacharytsenghy@gmail.com,BC/AB: Volunteer Success Program,2025-10-14 17:30:00,2025-10-14 17:45:00,True,Invitee
1328,Zachary Tseng,Zachary,Tseng,zacharytsenghy@gmail.com,BC/AB: Volunteer Success Program,2025-10-14 17:30:00,2025-10-14 17:45:00,True,Host

In [21]:
interview_combined = interview_combined.drop_duplicates(
    subset=['Invitee Name', 'Start Date & Time', 'End Date & Time'],  # 此处的分析我更为严谨，因为害怕其他列比如空格分布不均，字符大小写拼错导致一整行重复去drop失效！
    keep='first'
)

In [22]:
interview_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2867 entries, 0 to 2898
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Invitee Name        2867 non-null   object
 1   Invitee First Name  2867 non-null   object
 2   Invitee Last Name   2491 non-null   object
 3   Invitee Email       2867 non-null   object
 4   Event Type Name     2867 non-null   object
 5   Start Date & Time   2867 non-null   datetime64[ns]
 6   End Date & Time     2867 non-null   datetime64[ns]
 7   Canceled            2867 non-null   bool
 8   Canceled By         676 non-null    object
dtypes: bool(1), datetime64[ns](2), object(6)
memory usage: 204.4+ KB

In [23]:
interview_combined.head()

,Invitee Name,Invitee First Name,Invitee Last Name,Invitee Email,Event Type Name,Start Date & Time,End Date & Time,Canceled,Canceled By
0,Baani Singh,Baani,Singh,baanii.singh@gmail.com,ON: Volunteer Success Program,2025-03-11 16:45:00,2025-03-11 17:00:00,True,Host
1,Alisa Khvostiuk,Alisa,Khvostiuk,alisa.khvostiuk@gmail.com,ON: Volunteer Success Program,2025-03-03 15:00:00,2025-03-03 15:15:00,False,NaN
2,Ryan Yang,Ryan,Yang,ryan.y2912@gmail.com,ON: Volunteer Success Program,2025-03-03 15:45:00,2025-03-03 16:00:00,False,NaN
3,Baani Singh,Baani,Singh,baanii.singh@gmail.com,ON: Volunteer Success Program,2025-03-06 16:15:00,2025-03-06 16:30:00,False,NaN
4,Mya Charlotte Wong,Mya,Charlotte Wong,vecchiamya@gmail.com,ON: Volunteer Success Program,2025-03-03 15:30:00,2025-03-03 15:45:00,False,NaN

In [24]:
interview_combined['Invitee Email'] = interview_combined['Invitee Email'].str.strip().str.lower()

In [25]:
interview_combined['Invitee Email'].duplicated().sum()

np.int64(775)

In [26]:
interview_combined['Invitee Name'].duplicated().sum()

np.int64(747)

In [27]:
# 说明数据出现重复面试的人选，有些人重复面试了项目！因此根据第一题简化需求！
interview_unique_emails_for_case1 = interview_combined.drop_duplicates(subset=['Invitee Email'], keep='first').copy()

In [28]:
# 好了，到此这步，interview_unqiue_emails应该是能否合理使用了！

In [29]:
# 接下来开始清洗VSP表格！

In [30]:
vsp['Name'] = vsp['Name'].str.strip().str.title()

In [31]:
vsp['Email Address'] = vsp['Email Address'].str.strip().str.lower()

In [32]:
vsp['YRES Email'] = vsp['YRES Email'].str.strip().str.lower()

In [33]:
vsp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2893 entries, 0 to 2892
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Name                           2893 non-null   object
 1   Creation log                   2893 non-null   object
 2   Email Address                  2882 non-null   object
 3   YRES Email                     2279 non-null   object
 4   Contacted on Slack             943 non-null    object
 5   Interview Status               2091 non-null   object
 6   Youth Advisor 3 - Winter 2026  1883 non-null   object
 7   Placement Status               2893 non-null   object
 8   Volunteer Status               1370 non-null   object
 9   Share account info             985 non-null    object
dtypes: object(10)
memory usage: 226.1+ KB

In [34]:
vsp['Email Address'].isnull().sum()

np.int64(11)

In [35]:
vsp['Email Address'].duplicated().sum()

np.int64(113)

In [36]:
# 发现在vsp表格中出现重复邮箱，依然说明有申请者重复进入了YRES组织，无意义复数次登记！因此需要删除！

In [37]:
vsp_cleaned_for_case1 = vsp.dropna(subset=['Email Address']).copy()

# 2. 删掉 Email 重复的行（保留第一个人，避免数据膨胀）
vsp_cleaned_for_case1 = vsp_cleaned_for_case1.drop_duplicates(subset=['Email Address'], keep='first')

# 3. 统计一下现在还剩多少人
print(f"最终参与分析的 VSP 志愿者人数: {len(vsp_cleaned_for_case1)}")

最终参与分析的 VSP 志愿者人数: 2779

In [38]:
# 1. 执行 Left Join
case1_merged = pd.merge(
    vsp_cleaned_for_case1, 
    interview_unique_emails_for_case1, 
    left_on='Email Address', 
    right_on='Invitee Email', 
    how='left'
)

In [39]:
not_booked = case1_merged[case1_merged['Invitee Email'].isnull()].copy()

In [40]:
not_booked

,Name,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info,Invitee Name,Invitee First Name,Invitee Last Name,Invitee Email,Event Type Name,Start Date & Time,End Date & Time,Canceled,Canceled By
0,Mariam Ali,"U+ HR Account Sep 11, 2025 1:30 PM",mariam.ali@yorkeducation.ca,yafet.hailu@yorkeducation.ca,NaN,NaN,Bella He,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
1,Manusha Srikanthan,"Jess Scott Sep 11, 2025 1:45 PM",manushasrikanthan@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
3,Dorsey Bangarh,"Jess Scott Sep 11, 2025 5:37 PM",dorseybangarh2004@gmail.com,dorsey.bangarh@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
4,Pushti Ladani,"Jess Scott Sep 11, 2025 7:26 PM",pushti-kantilal.ladani@mohawkcollege.ca,pushti.ladani@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
5,Purti Ladani,"Jess Scott Sep 11, 2025 7:29 PM",purti1002@gmail.com,purti.ladani@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2774,Chinelo Ugwu,"Kevin Feb 27, 2026 8:54 AM",nelonilar024@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
2775,Kehinde Alegu Adesola,"Kevin Mar 4, 2026 11:23 AM",adenugakehinde55@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
2776,Sadequi Houssam Eddine,"Kevin Mar 10, 2026 9:21 PM",divhoussam@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
2777,Kouceila Sadoudi,"Kevin Mar 21, 2026 10:40 PM",kouceilasad@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN
2778,Hamza Wafa,"Kevin Mar 31, 2026 2:40 PM",mnsrotsomiya@gmail.com,NaN,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN

In [41]:
answer_q1 = not_booked[['Name', 'Email Address', 'Creation log','Share account info','Contacted on Slack','Interview Status','Placement Status','Volunteer Status']].copy()

In [42]:
answer_q1.head()

,Name,Email Address,Creation log,Share account info,Contacted on Slack,Interview Status,Placement Status,Volunteer Status
0,Mariam Ali,mariam.ali@yorkeducation.ca,"U+ HR Account Sep 11, 2025 1:30 PM",NaN,NaN,NaN,Waiting To Be Placed,NaN
1,Manusha Srikanthan,manushasrikanthan@gmail.com,"Jess Scott Sep 11, 2025 1:45 PM",NaN,NaN,NaN,Waiting To Be Placed,NaN
3,Dorsey Bangarh,dorseybangarh2004@gmail.com,"Jess Scott Sep 11, 2025 5:37 PM",NaN,NaN,NaN,Waiting To Be Placed,NaN
4,Pushti Ladani,pushti-kantilal.ladani@mohawkcollege.ca,"Jess Scott Sep 11, 2025 7:26 PM",NaN,NaN,NaN,Waiting To Be Placed,NaN
5,Purti Ladani,purti1002@gmail.com,"Jess Scott Sep 11, 2025 7:29 PM",NaN,NaN,NaN,Waiting To Be Placed,NaN

### 此处记得导出！

### Q2 Among all VSP volunteers who have been interviewed, who haven’t been invited to Slack?

In [43]:
# 先对VSP表格进行操作！
vsp_interviewed = vsp[vsp['Youth Advisor 3 - Winter 2026'].notnull()].copy()

In [44]:
vsp_interviewed = vsp_interviewed.dropna(subset=['YRES Email'])

In [45]:
vsp_interviewed = vsp_interviewed.drop_duplicates(subset=['Name','Email Address', 'YRES Email'], keep='first')

In [46]:
vsp_interviewed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1859 entries, 0 to 2887
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Name                           1859 non-null   object
 1   Creation log                   1859 non-null   object
 2   Email Address                  1859 non-null   object
 3   YRES Email                     1859 non-null   object
 4   Contacted on Slack             942 non-null    object
 5   Interview Status               1807 non-null   object
 6   Youth Advisor 3 - Winter 2026  1859 non-null   object
 7   Placement Status               1859 non-null   object
 8   Volunteer Status               1268 non-null   object
 9   Share account info             983 non-null    object
dtypes: object(10)
memory usage: 159.8+ KB

In [47]:
vsp_interviewed.isna().sum()

Name                               0
Creation log                       0
Email Address                      0
YRES Email                         0
Contacted on Slack               917
Interview Status                  52
Youth Advisor 3 - Winter 2026      0
Placement Status                   0
Volunteer Status                 591
Share account info               876
dtype: int64

In [48]:
vsp_interviewed['YRES Email'].duplicated().sum()

np.int64(2)

### 此处是根据Q3反过来改进后，后续做一样的任务时候不用再加这段注释了！

In [49]:
vsp_interviewed.duplicated().sum()

np.int64(0)

In [50]:
vsp_interviewed.shape

(1859, 10)

In [51]:
# 现在开始清洗Acitvity表格！

In [52]:
activity.head(20)

,Name,Display name,Email,Account type,Account created (UTC),Days active,Messages posted,Messages posted in channels,Reactions added,Last active (UTC)
0,(Vol. Leader) Victoria H.,(Vol. Leader) Victoria H.,iivv.berry@gmail.com,Member,2023-04-14,0,0,0,0,NaT
1,(Vol. Leader) Zainab Ahmed,Zainab,zainab.ahmed@yorkeducation.ca,Member,2023-04-14,2,1,0,0,2026-03-16
2,Aadam Lakhani,Aadam Lakhani,aadam.lakhani@yorkeducation.ca,Member,2023-09-16,0,0,0,0,NaT
3,Aadhya Sriram,Aadhya Sriram,aadhya.sriram@yorkeducation.ca,Member,2023-11-08,0,0,0,0,2024-08-02
4,Aakanksha,Aakanksha,aakanksha.patel@yorkeducation.ca,Member,2025-07-25,0,0,0,0,2025-11-20
5,Aakash Parwani,Aakash Parwani,aakash.parwani@yorkeducation.ca,Member,2026-01-22,4,0,0,0,2026-03-20
6,Aali Vaqar,Aali Vaqar,aali.vaqarahmad@yorkeducation.ca,Member,2025-04-16,0,0,0,0,2025-04-29
7,Aanchal Ratha,Aanchal Ratha,aanchal.ratha@yorkeducation.ca,Member,2023-11-07,0,0,0,0,2024-12-11
8,Aanushan Elangoban,Aanushan Elangoban,aanushan.elangoban@upluseducation.ca,Invited Member,2026-03-21,0,0,0,0,NaT
9,Aanushan Elangoban,Aanushan Elangoban,aanushan.elangoban@yorkeducation.ca,Admin,2025-06-27,26,300,26,71,2026-03-30
10,Aanushan Elangoban,Aanushan Elangoban,aanushan.236@gmail.com,Admin,2025-09-14,0,0,0,0,2025-09-14
11,Aaradhya Atul Yeginwar,Aaradhya Atul Yeginwar,aaradhya@yorkeducation.ca,Member,2025-06-01,0,0,0,0,2025-10-28
12,Aaran Rajkanth,Aaran Rajkanth,aaranrajkanth@yorkeducation.ca,Member,2025-06-15,1,0,0,0,2026-03-20
13,Aarathy Thayagunan,Aarathy Thayagunan,aarathy.thayagunan@yorkeducation.ca,Invited Member,2023-04-26,0,0,0,0,NaT
14,Aarav Modi,Aarav Modi,aarav.modi@yorkeducation.ca,Member,2023-07-10,0,0,0,0,NaT
15,Aarna Tyagi,Aarna,aarna.tyagi@yorkeducation.ca,Member,2026-01-16,0,0,0,0,2026-02-24
16,Aaron Boateng,Aaron Boateng,aaron.boateng@yorkeducation.ca,Invited Member,2026-01-09,0,0,0,0,NaT
17,Aaron Fernandez,Aaron Fernandez,aaron.fernandez@yorkeducation.ca,Invited Member,2023-04-26,0,0,0,0,NaT
18,Aaron Lai,Aaron Lai,aaron.lai@yorkeducation.ca,Member,2025-06-05,0,0,0,0,2025-11-14
19,Aaron Qian,Aaron Qian,aaron.qian@yorkeducation.ca,Member,2025-02-01,0,0,0,0,2025-05-13

In [53]:
activity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3131 entries, 0 to 3130
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         3131 non-null   object
 1   Display name                 3131 non-null   object
 2   Email                        3131 non-null   object
 3   Account type                 3131 non-null   object
 4   Account created (UTC)        3131 non-null   datetime64[ns]
 5   Days active                  3131 non-null   int64
 6   Messages posted              3131 non-null   int64
 7   Messages posted in channels  3131 non-null   int64
 8   Reactions added              3131 non-null   int64
 9   Last active (UTC)            2016 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(4), object(4)
memory usage: 244.7+ KB

In [54]:
activity['Name'] = activity['Name'].str.strip().str.title()
activity['Display name'] = activity['Display name'].str.strip().str.title()

In [55]:
activity['Email'] = activity['Email'].str.strip().str.lower()

In [56]:
activity['Account type'].unique()

array(['Member', 'Invited Member', 'Admin', 'Owner'], dtype=object)

In [57]:
activity_cleaned = activity.drop_duplicates().copy()

In [58]:
print(f"原始行数: {len(activity)}")
print(f"全行去重后行数: {len(activity_cleaned)}")

原始行数: 3131
全行去重后行数: 3131

In [59]:
activity_cleaned['Email'].duplicated().sum()

np.int64(0)

In [60]:
activity_cleaned['Email'].isna().sum()

np.int64(0)

In [61]:
q2_merged = pd.merge(
    vsp_interviewed,
    activity_cleaned,
    left_on = 'YRES Email',
    right_on = 'Email',
    how = 'left'
)

In [62]:
q2_merged

,Name_x,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info,Name_y,Display name,Email,Account type,Account created (UTC),Days active,Messages posted,Messages posted in channels,Reactions added,Last active (UTC)
0,Mariam Ali,"U+ HR Account Sep 11, 2025 1:30 PM",mariam.ali@yorkeducation.ca,yafet.hailu@yorkeducation.ca,NaN,NaN,Bella He,Waiting To Be Placed,NaN,NaN,Yafet Hailu,Yafet Hailu,yafet.hailu@yorkeducation.ca,Member,2026-03-01,21.0,11.0,5.0,0.0,2026-03-30
1,Harvi Shah,"Jess Scott Sep 11, 2025 4:36 PM",harvishah2602@gmail.com,harvi.shah@yorkeducation.ca,Done,Interviewed,Tiffany Ye,In-training,Active,NaN,Harvishah,Harvishah,harvi.shah@yorkeducation.ca,Member,2025-10-19,0.0,0.0,0.0,0.0,2025-11-12
2,Harjot Singh,"Jess Scott Sep 11, 2025 8:52 PM",singhharjot1312@gmail.com,harjot.singh@yorkeducation.ca,NaN,Interviewed,Aanushan Elangoban,Unresponsive,Continue?,Email sent,Harjot Singh,Harjot Singh,harjot.singh@yorkeducation.ca,Member,2025-09-29,4.0,4.0,1.0,0.0,2026-03-27
3,Jeehu Choi,"Jess Scott Sep 11, 2025 8:55 PM",jiwhotwin@gmail.com,jeehu.choi@yorkeducation.ca,NaN,Interviewed,Bella He,Waiting To Be Placed,Continue?,Shared in call,Jeehu Choi,Jeehu Choi,jeehu.choi@yorkeducation.ca,Member,2025-10-04,0.0,0.0,0.0,0.0,2025-10-04
4,Taranveer Arora,"Jess Scott Sep 11, 2025 9:32 PM",taransarora@gmail.com,taranveer.arora@yorkeducation.ca,NaN,Interviewed,Bryna McGarrigle,Placed,Active,Shared in call,Taran Arora,Taran Arora,taranveer.arora@yorkeducation.ca,Member,2025-09-27,2.0,0.0,0.0,0.0,2026-03-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1854,Vivian Anumba,"Jess Scott Oct 5, 2025 7:14 AM",viviananumba2021@gmail.com,vivian.anumba@yorkeducation.ca,NaN,Interviewed,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,Shared in call,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1855,Klia Nassr Allah,"Jess Scott Oct 6, 2025 12:01 AM",nassrokl215@gmail.com,klia.nassr.allah@yorkeducation.ca,NaN,Interviewed,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,Email sent,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1856,Melody Gramajo,"Jess Scott Oct 22, 2025 5:11 PM",celesmedready@gmail.com,melody.gramajo@yorkeducation.ca,Done,Interviewed,Chelzy Evangelista,Placed,Withdrawn,Shared in call,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1857,Hemangi Rane,"Jess Scott Dec 11, 2025 4:44 AM",hemangi.inbox@gmail.com,hemangi.rane@yorkeducation.ca,NaN,Interviewed,Jing Zhang,Waiting To Be Placed,NaN,NaN,Hemangi Rane,Hemangi Rane,hemangi.rane@yorkeducation.ca,Invited Member,2025-12-12,0.0,0.0,0.0,0.0,NaT
1858,Bassirou Sagna,"Volunteer account Feb 5, 2026 5:45 AM",bassirou_sagna@yahoo.com,bassirou.sagna@yorkeducation.ca,NaN,NaN,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,NaN,Bassirou Sagna,Bassirou Sagna,bassirou.sagna@yorkeducation.ca,Invited Member,2026-02-05,0.0,0.0,0.0,0.0,NaT

In [63]:
not_in_slack = q2_merged[q2_merged['Email'].isnull()].copy()

In [64]:
print(f"已面试志愿者总数: {len(vsp_interviewed)}")
print(f"未加入 Slack 的人数: {len(not_in_slack)}")

已面试志愿者总数: 1859
未加入 Slack 的人数: 130

In [65]:
not_in_slack

,Name_x,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info,Name_y,Display name,Email,Account type,Account created (UTC),Days active,Messages posted,Messages posted in channels,Reactions added,Last active (UTC)
10,Olina Zheng,"Jess Scott Sep 13, 2025 3:39 PM",olinazheng10@gmail.com,olina.zheng@yorkeducation.ca,NaN,Interviewed,Bella He,Placed,Withdrawn,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
12,Arbind Boparai,"Jess Scott Sep 13, 2025 3:41 PM",arbindkboparai@hotmail.com,arbind.boparai@yorkeducation.ca,Done,Interviewed,Tiffany Ye,Placed,Active,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
93,Kayla Orellana,"Jess Scott Sep 26, 2025 7:13 AM",kaylaorellana33@gmail.com,kayla.orellana@yorkeducation.ca,Remind to join Slack,Interviewed,Aanushan Elangoban,Unresponsive,Continue?,Shared in call,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
107,Daiyan Odhi,"Jess Scott Sep 29, 2025 11:34 AM",daiyanodhi67@gmail.com,daiyan.odhi@yorkeducation.ca,NaN,No Show,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
111,Janooshan Ravichandran,"Jess Scott Sep 29, 2025 10:03 PM",janooshan.r@gmail.com,janooshan.ravichandran@yorkeducation.ca,Remind to join Slack,Interviewed,Aanushan Elangoban,Unresponsive,Continue?,Need to email,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852,Ahmed Yasser,"Jess Scott Sep 23, 2025 11:15 PM",ahmed.yasser.email@gmail.com,ahmed.yasser@yorkeducation.ca,NaN,Interviewed,Damon Carmen Tran,Placed,Withdrawn,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1853,Mariseni Thelma Nakai,"Jess Scott Oct 1, 2025 1:08 AM",marisenithelmanakai@gmail.com,mariseni.nakai@yorkeducation.ca,NaN,Interviewed,Aanushan Elangoban,Unresponsive,Withdrawn,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1854,Vivian Anumba,"Jess Scott Oct 5, 2025 7:14 AM",viviananumba2021@gmail.com,vivian.anumba@yorkeducation.ca,NaN,Interviewed,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,Shared in call,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1855,Klia Nassr Allah,"Jess Scott Oct 6, 2025 12:01 AM",nassrokl215@gmail.com,klia.nassr.allah@yorkeducation.ca,NaN,Interviewed,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,Email sent,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
1856,Melody Gramajo,"Jess Scott Oct 22, 2025 5:11 PM",celesmedready@gmail.com,melody.gramajo@yorkeducation.ca,Done,Interviewed,Chelzy Evangelista,Placed,Withdrawn,Shared in call,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT

In [66]:
answer_q2 = not_in_slack[['Name_x', 'Email Address', 'YRES Email', 'Youth Advisor 3 - Winter 2026', 'Creation log','Share account info','Contacted on Slack', 'Interview Status',	'Placement Status', 'Volunteer Status']].copy()

In [67]:
answer_q2

,Name_x,Email Address,YRES Email,Youth Advisor 3 - Winter 2026,Creation log,Share account info,Contacted on Slack,Interview Status,Placement Status,Volunteer Status
10,Olina Zheng,olinazheng10@gmail.com,olina.zheng@yorkeducation.ca,Bella He,"Jess Scott Sep 13, 2025 3:39 PM",NaN,NaN,Interviewed,Placed,Withdrawn
12,Arbind Boparai,arbindkboparai@hotmail.com,arbind.boparai@yorkeducation.ca,Tiffany Ye,"Jess Scott Sep 13, 2025 3:41 PM",NaN,Done,Interviewed,Placed,Active
93,Kayla Orellana,kaylaorellana33@gmail.com,kayla.orellana@yorkeducation.ca,Aanushan Elangoban,"Jess Scott Sep 26, 2025 7:13 AM",Shared in call,Remind to join Slack,Interviewed,Unresponsive,Continue?
107,Daiyan Odhi,daiyanodhi67@gmail.com,daiyan.odhi@yorkeducation.ca,Damon Carmen Tran,"Jess Scott Sep 29, 2025 11:34 AM",NaN,NaN,No Show,Waiting To Be Placed,Withdrawn
111,Janooshan Ravichandran,janooshan.r@gmail.com,janooshan.ravichandran@yorkeducation.ca,Aanushan Elangoban,"Jess Scott Sep 29, 2025 10:03 PM",Need to email,Remind to join Slack,Interviewed,Unresponsive,Continue?
...,...,...,...,...,...,...,...,...,...,...
1852,Ahmed Yasser,ahmed.yasser.email@gmail.com,ahmed.yasser@yorkeducation.ca,Damon Carmen Tran,"Jess Scott Sep 23, 2025 11:15 PM",NaN,NaN,Interviewed,Placed,Withdrawn
1853,Mariseni Thelma Nakai,marisenithelmanakai@gmail.com,mariseni.nakai@yorkeducation.ca,Aanushan Elangoban,"Jess Scott Oct 1, 2025 1:08 AM",NaN,NaN,Interviewed,Unresponsive,Withdrawn
1854,Vivian Anumba,viviananumba2021@gmail.com,vivian.anumba@yorkeducation.ca,Damon Carmen Tran,"Jess Scott Oct 5, 2025 7:14 AM",Shared in call,NaN,Interviewed,Waiting To Be Placed,Withdrawn
1855,Klia Nassr Allah,nassrokl215@gmail.com,klia.nassr.allah@yorkeducation.ca,Damon Carmen Tran,"Jess Scott Oct 6, 2025 12:01 AM",Email sent,NaN,Interviewed,Waiting To Be Placed,Withdrawn
1856,Melody Gramajo,celesmedready@gmail.com,melody.gramajo@yorkeducation.ca,Chelzy Evangelista,"Jess Scott Oct 22, 2025 5:11 PM",Shared in call,Done,Interviewed,Placed,Withdrawn

### 记得导出答案文件！

### Q3 Among all VSP volunteers, who are invited to Slack but never joined?

In [68]:
vsp['YRES Email'].duplicated().sum()

np.int64(644)

In [69]:
activity_cleaned['Email'].duplicated().sum()

np.int64(0)

In [70]:
vsp_cleaned_for_case3 = vsp.dropna(subset=['YRES Email']).copy()

vsp_cleaned_for_case3 = vsp_cleaned_for_case3.drop_duplicates(subset=['Name','Email Address','YRES Email'], keep='first')

In [71]:
vsp_cleaned_for_case3['YRES Email'].duplicated().sum()

np.int64(6)

In [72]:
vsp_cleaned_for_case3[vsp_cleaned_for_case3['YRES Email'].duplicated(keep=False)]

,Name,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info
0,Mariam Ali,"U+ HR Account Sep 11, 2025 1:30 PM",mariam.ali@yorkeducation.ca,yafet.hailu@yorkeducation.ca,NaN,NaN,Bella He,Waiting To Be Placed,NaN,NaN
316,Yuhan Zhuang,"Jess Scott Oct 15, 2025 4:00 AM",rainezhuang@gmail.com,yuhan.zhuang@yorkeducation.ca,Done,Interviewed,Tiffany Ye,Waiting To Be Placed,Active,Shared in call
446,Alyssa Yang,"Deleted member Aug 11, 2025 11:56 AM",NaN,alyssa.yang@yorkeducation.ca,NaN,Unbooked,NaN,Waiting To Be Placed,NaN,NaN
581,Duaa Ali,"Jess Scott Mar 20, 2025 2:47 PM",duaadmkd19@gmail.com,duaa.ali@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN
982,Alyssa Yang,"Jess Scott Aug 4, 2025 1:07 PM",alyssayang18@gmail.com,alyssa.yang@yorkeducation.ca,Done,Interviewed,Jing Zhang,Placed,Active,NaN
1222,Mya Charlotte Wong,"Volunteer account Mar 26, 2025 5:39 PM",vecchiamya@gmail.com,mya.wong@yorkeducation.ca,NaN,Interviewed,NaN,Placed,Hold,NaN
1429,Yutong Zhu,"Jess Scott May 25, 2025 11:28 AM",wuannie1230@gmail.com,yutong@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN
1431,Shannon Chiong,"Jess Scott May 26, 2025 8:20 PM",shannonchiong@gmail.com,yutong@yorkeducation.ca,NaN,Unbooked,NaN,Waiting To Be Placed,NaN,NaN
1494,Raine Zhuang (Yuhan Zhuang),"Jess Scott Oct 26, 2025 6:13 PM",yuhan.zhuang@yorkeducation.ca,yuhan.zhuang@yorkeducation.ca,Done,Interviewed,Tiffany Ye,In-training,Active,Shared in call
1797,Duaa Ali,"Jess Scott Mar 17, 2025 1:31 PM",duaa.ali@upluseducation.ca,duaa.ali@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,Withdrawn,NaN
2180,Mya Wong,"Kevin Feb 14, 2026 8:08 PM",vecchiamya@gmail.com,mya.wong@yorkeducation.ca,NaN,Interviewed,Aanushan Elangoban,Waiting To Be Placed,NaN,Email sent
2279,Yafet Hailu,"Kevin Feb 27, 2026 8:38 AM",yafetthailu@gmail.com,yafet.hailu@yorkeducation.ca,Done,Interviewed,Bella He,Waiting To Be Placed,Active,Email sent

# 这个是我发现的数据异常！根本项目无关！我先通知下Supervisor！

# 导出这 12 行重复/冲突数据
vsp_data_issues = vsp_cleaned_for_case3[vsp_cleaned_for_case3['YRES Email'].duplicated(keep=False)]
vsp_data_issues = vsp_data_issues.sort_values(by='YRES Email')
vsp_data_issues.to_excel("VSP_Data_Integrity_Alert.xlsx", index=True)

In [73]:
q3_merged = pd.merge(
    vsp_cleaned_for_case3,
    activity_cleaned,
    left_on = 'YRES Email',
    right_on = 'Email',
    how = 'left'
)

In [74]:
answer_q3 = q3_merged[q3_merged['Account type'] == 'Invited Member'].copy()

In [75]:
answer_q3

,Name_x,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info,Name_y,Display name,Email,Account type,Account created (UTC),Days active,Messages posted,Messages posted in channels,Reactions added,Last active (UTC)
30,Chik Fu Fung,"Jess Scott Sep 14, 2025 12:44 AM",chikf666@gmail.com,chik.fu.fung@yorkeducation.ca,NaN,NaN,Chelzy Evangelista,Waiting To Be Placed,Continue?,NaN,Chik Fu Fung,Chik Fu Fung,chik.fu.fung@yorkeducation.ca,Invited Member,2025-10-17,0.0,0.0,0.0,0.0,NaT
46,Samir Altakhin,"Jess Scott Sep 17, 2025 12:23 PM",takhinsamir@gmail.com,samir.altakhin@yorkeducation.ca,Remind to join Slack,Interviewed,Jing Zhang,In-training,Active,Email sent,Samir Altakhin,Samir Altakhin,samir.altakhin@yorkeducation.ca,Invited Member,2025-09-26,0.0,0.0,0.0,0.0,NaT
47,Wahenoor Kaur,"Jess Scott Sep 15, 2025 11:32 PM",wahenoork2009@gmail.com,wahenoor.kaur@yorkeducation.ca,NaN,No Show,Chelzy Evangelista,Waiting To Be Placed,Continue?,NaN,Wahenoor Kaur,Wahenoor Kaur,wahenoor.kaur@yorkeducation.ca,Invited Member,2025-10-04,0.0,0.0,0.0,0.0,NaT
49,Safaet Ahmed,"Jess Scott Sep 16, 2025 7:18 AM",safaetahmed.00@gmail.com,safaet.ahmed@yorkeducation.ca,NaN,No Show,Jing Zhang,Waiting To Be Placed,NaN,NaN,Safaet Ahmed,Safaet Ahmed,safaet.ahmed@yorkeducation.ca,Invited Member,2025-10-03,0.0,0.0,0.0,0.0,NaT
58,Yash Kavale,"Jess Scott Sep 17, 2025 3:03 PM",yashkavale9@gmail.com,yash.kavale@yorkeducation.ca,NaN,No Show,Damon Carmen Tran,Waiting To Be Placed,NaN,NaN,Yash Kavale,Yash Kavale,yash.kavale@yorkeducation.ca,Invited Member,2026-01-09,0.0,0.0,0.0,0.0,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,Nafis Kamaree,"Kevin Mar 12, 2026 7:40 PM",nafisinfo2357@gmail.com,nafis.kamaree@yorkeducation.ca,NaN,No Show,Chelzy Evangelista,Waiting To Be Placed,NaN,NaN,Nafis Kamaree,Nafis Kamaree,nafis.kamaree@yorkeducation.ca,Invited Member,2026-03-27,0.0,0.0,0.0,0.0,NaT
2238,Ahmed Hossam Faisal Abdelbassit,"Jess Scott Sep 17, 2025 3:38 AM",medoaboelnasr065@gmail.com,ahmed.hossam.faisal.abdelbassit@yorkeducation.ca,NaN,No Show,NaN,Waiting To Be Placed,Withdrawn,NaN,Ahmed Hossam Faisal Abdelbassit,Ahmed Hossam Faisal Abdelbassit,ahmed.hossam.faisal.abdelbassit@yorkeducation.ca,Invited Member,2025-10-19,0.0,0.0,0.0,0.0,NaT
2248,Fredrick Mulema,"Jess Scott Mar 16, 2025 10:17 AM",mulema1975@gmail.com,fredrick.mulema@yorkeducation.ca,NaN,No Show,NaN,Waiting To Be Placed,Withdrawn,NaN,Fredrick Mulema,Fredrick Mulema,fredrick.mulema@yorkeducation.ca,Invited Member,2025-05-15,0.0,0.0,0.0,0.0,NaT
2252,Hemangi Rane,"Jess Scott Dec 11, 2025 4:44 AM",hemangi.inbox@gmail.com,hemangi.rane@yorkeducation.ca,NaN,Interviewed,Jing Zhang,Waiting To Be Placed,NaN,NaN,Hemangi Rane,Hemangi Rane,hemangi.rane@yorkeducation.ca,Invited Member,2025-12-12,0.0,0.0,0.0,0.0,NaT
2253,Bassirou Sagna,"Volunteer account Feb 5, 2026 5:45 AM",bassirou_sagna@yahoo.com,bassirou.sagna@yorkeducation.ca,NaN,NaN,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,NaN,Bassirou Sagna,Bassirou Sagna,bassirou.sagna@yorkeducation.ca,Invited Member,2026-02-05,0.0,0.0,0.0,0.0,NaT

In [76]:
answer_q3 = answer_q3[['Name_x', 'Email Address', 'YRES Email', 'Youth Advisor 3 - Winter 2026', 'Account type','Creation log','Share account info','Contacted on Slack', 'Interview Status',	'Placement Status', 'Volunteer Status']]

In [77]:
answer_q3

,Name_x,Email Address,YRES Email,Youth Advisor 3 - Winter 2026,Account type,Creation log,Share account info,Contacted on Slack,Interview Status,Placement Status,Volunteer Status
30,Chik Fu Fung,chikf666@gmail.com,chik.fu.fung@yorkeducation.ca,Chelzy Evangelista,Invited Member,"Jess Scott Sep 14, 2025 12:44 AM",NaN,NaN,NaN,Waiting To Be Placed,Continue?
46,Samir Altakhin,takhinsamir@gmail.com,samir.altakhin@yorkeducation.ca,Jing Zhang,Invited Member,"Jess Scott Sep 17, 2025 12:23 PM",Email sent,Remind to join Slack,Interviewed,In-training,Active
47,Wahenoor Kaur,wahenoork2009@gmail.com,wahenoor.kaur@yorkeducation.ca,Chelzy Evangelista,Invited Member,"Jess Scott Sep 15, 2025 11:32 PM",NaN,NaN,No Show,Waiting To Be Placed,Continue?
49,Safaet Ahmed,safaetahmed.00@gmail.com,safaet.ahmed@yorkeducation.ca,Jing Zhang,Invited Member,"Jess Scott Sep 16, 2025 7:18 AM",NaN,NaN,No Show,Waiting To Be Placed,NaN
58,Yash Kavale,yashkavale9@gmail.com,yash.kavale@yorkeducation.ca,Damon Carmen Tran,Invited Member,"Jess Scott Sep 17, 2025 3:03 PM",NaN,NaN,No Show,Waiting To Be Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2228,Nafis Kamaree,nafisinfo2357@gmail.com,nafis.kamaree@yorkeducation.ca,Chelzy Evangelista,Invited Member,"Kevin Mar 12, 2026 7:40 PM",NaN,NaN,No Show,Waiting To Be Placed,NaN
2238,Ahmed Hossam Faisal Abdelbassit,medoaboelnasr065@gmail.com,ahmed.hossam.faisal.abdelbassit@yorkeducation.ca,NaN,Invited Member,"Jess Scott Sep 17, 2025 3:38 AM",NaN,NaN,No Show,Waiting To Be Placed,Withdrawn
2248,Fredrick Mulema,mulema1975@gmail.com,fredrick.mulema@yorkeducation.ca,NaN,Invited Member,"Jess Scott Mar 16, 2025 10:17 AM",NaN,NaN,No Show,Waiting To Be Placed,Withdrawn
2252,Hemangi Rane,hemangi.inbox@gmail.com,hemangi.rane@yorkeducation.ca,Jing Zhang,Invited Member,"Jess Scott Dec 11, 2025 4:44 AM",NaN,NaN,Interviewed,Waiting To Be Placed,NaN
2253,Bassirou Sagna,bassirou_sagna@yahoo.com,bassirou.sagna@yorkeducation.ca,Damon Carmen Tran,Invited Member,"Volunteer account Feb 5, 2026 5:45 AM",NaN,NaN,NaN,Waiting To Be Placed,Withdrawn

### Q4 Among all VSP volunteers who are on Slack already, who hasn’t been active in the past two month

In [78]:
q4_merged = q3_merged.copy()

In [79]:
q4_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2254 entries, 0 to 2253
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Name_x                         2254 non-null   object
 1   Creation log                   2254 non-null   object
 2   Email Address                  2253 non-null   object
 3   YRES Email                     2254 non-null   object
 4   Contacted on Slack             941 non-null    object
 5   Interview Status               2068 non-null   object
 6   Youth Advisor 3 - Winter 2026  1858 non-null   object
 7   Placement Status               2254 non-null   object
 8   Volunteer Status               1314 non-null   object
 9   Share account info             984 non-null    object
 10  Name_y                         1761 non-null   object
 11  Display name                   1761 non-null   object
 12  Email                          1761 non-null   object
 13  Account type                   1761 non-null   object
 14  Account created (UTC)          1761 non-null   datetime64[ns]
 15  Days active                    1761 non-null   float64
 16  Messages posted                1761 non-null   float64
 17  Messages posted in channels    1761 non-null   float64
 18  Reactions added                1761 non-null   float64
 19  Last active (UTC)              1556 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(4), object(14)
memory usage: 352.3+ KB

In [80]:
deadline = pd.Timestamp('2026-02-01')

In [81]:
# 1. 筛选条件：有账号（Account type 存在）且（活跃时间早于2月1日 或 从未活跃）
#已经事先检查过Account type在event activity dataset中不存在空值unique！所以可以江merge中与其他没有slack记录也就是前面第二题的人分开！
q4_answer = q4_merged[
    (q4_merged['Account type'].notnull()) & 
    ((q4_merged['Last active (UTC)'] < deadline) | (q4_merged['Last active (UTC)'].isnull()))
].copy()

In [82]:
q4_answer

,Name_x,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info,Name_y,Display name,Email,Account type,Account created (UTC),Days active,Messages posted,Messages posted in channels,Reactions added,Last active (UTC)
1,Harvi Shah,"Jess Scott Sep 11, 2025 4:36 PM",harvishah2602@gmail.com,harvi.shah@yorkeducation.ca,Done,Interviewed,Tiffany Ye,In-training,Active,NaN,Harvishah,Harvishah,harvi.shah@yorkeducation.ca,Member,2025-10-19,0.0,0.0,0.0,0.0,2025-11-12
7,Jeehu Choi,"Jess Scott Sep 11, 2025 8:55 PM",jiwhotwin@gmail.com,jeehu.choi@yorkeducation.ca,NaN,Interviewed,Bella He,Waiting To Be Placed,Continue?,Shared in call,Jeehu Choi,Jeehu Choi,jeehu.choi@yorkeducation.ca,Member,2025-10-04,0.0,0.0,0.0,0.0,2025-10-04
9,Luong Hai Ha Bui,"Jess Scott Sep 11, 2025 10:03 PM",habui151103@gmail.com,luong.hai.ha.bui@yorkeducation.ca,NaN,Interviewed,Bella He,Waiting To Be Placed,Continue?,Shared in call,Ha Bui,Ha Bui,luong.hai.ha.bui@yorkeducation.ca,Member,2025-09-27,0.0,0.0,0.0,0.0,2025-09-27
10,Pranav Kumar,"Jess Scott Sep 11, 2025 10:12 PM",pranav.in.kumar@gmail.com,pranav.kumar@yorkeducation.ca,Done,Interviewed,Jing Zhang,In-training,Withdrawn,Shared in call,Pranav Kumar,Pranav Kumar,pranav.kumar@yorkeducation.ca,Member,2025-10-01,0.0,0.0,0.0,0.0,2025-10-01
13,Alexander Artunduaga,"Jess Scott Sep 12, 2025 9:36 AM",alexander.artunduaga.1209@gmail.com,alexander.artunduaga@yorkeducation.ca,Done,Interviewed,Jing Zhang,In-training,Continue?,Email sent,Alexander Artunduaga,Alexander Artunduaga,alexander.artunduaga@yorkeducation.ca,Member,2025-09-26,0.0,0.0,0.0,0.0,2025-09-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,Nafis Kamaree,"Kevin Mar 12, 2026 7:40 PM",nafisinfo2357@gmail.com,nafis.kamaree@yorkeducation.ca,NaN,No Show,Chelzy Evangelista,Waiting To Be Placed,NaN,NaN,Nafis Kamaree,Nafis Kamaree,nafis.kamaree@yorkeducation.ca,Invited Member,2026-03-27,0.0,0.0,0.0,0.0,NaT
2238,Ahmed Hossam Faisal Abdelbassit,"Jess Scott Sep 17, 2025 3:38 AM",medoaboelnasr065@gmail.com,ahmed.hossam.faisal.abdelbassit@yorkeducation.ca,NaN,No Show,NaN,Waiting To Be Placed,Withdrawn,NaN,Ahmed Hossam Faisal Abdelbassit,Ahmed Hossam Faisal Abdelbassit,ahmed.hossam.faisal.abdelbassit@yorkeducation.ca,Invited Member,2025-10-19,0.0,0.0,0.0,0.0,NaT
2248,Fredrick Mulema,"Jess Scott Mar 16, 2025 10:17 AM",mulema1975@gmail.com,fredrick.mulema@yorkeducation.ca,NaN,No Show,NaN,Waiting To Be Placed,Withdrawn,NaN,Fredrick Mulema,Fredrick Mulema,fredrick.mulema@yorkeducation.ca,Invited Member,2025-05-15,0.0,0.0,0.0,0.0,NaT
2252,Hemangi Rane,"Jess Scott Dec 11, 2025 4:44 AM",hemangi.inbox@gmail.com,hemangi.rane@yorkeducation.ca,NaN,Interviewed,Jing Zhang,Waiting To Be Placed,NaN,NaN,Hemangi Rane,Hemangi Rane,hemangi.rane@yorkeducation.ca,Invited Member,2025-12-12,0.0,0.0,0.0,0.0,NaT
2253,Bassirou Sagna,"Volunteer account Feb 5, 2026 5:45 AM",bassirou_sagna@yahoo.com,bassirou.sagna@yorkeducation.ca,NaN,NaN,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,NaN,Bassirou Sagna,Bassirou Sagna,bassirou.sagna@yorkeducation.ca,Invited Member,2026-02-05,0.0,0.0,0.0,0.0,NaT

In [83]:
q4_answer = q4_answer[['Name_x', 'Email Address', 'YRES Email', 'Youth Advisor 3 - Winter 2026','Creation log', 'Last active (UTC)', 'Share account info','Contacted on Slack', 'Interview Status',	'Placement Status', 'Volunteer Status']]

In [84]:
q4_answer

,Name_x,Email Address,YRES Email,Youth Advisor 3 - Winter 2026,Creation log,Last active (UTC),Share account info,Contacted on Slack,Interview Status,Placement Status,Volunteer Status
1,Harvi Shah,harvishah2602@gmail.com,harvi.shah@yorkeducation.ca,Tiffany Ye,"Jess Scott Sep 11, 2025 4:36 PM",2025-11-12,NaN,Done,Interviewed,In-training,Active
7,Jeehu Choi,jiwhotwin@gmail.com,jeehu.choi@yorkeducation.ca,Bella He,"Jess Scott Sep 11, 2025 8:55 PM",2025-10-04,Shared in call,NaN,Interviewed,Waiting To Be Placed,Continue?
9,Luong Hai Ha Bui,habui151103@gmail.com,luong.hai.ha.bui@yorkeducation.ca,Bella He,"Jess Scott Sep 11, 2025 10:03 PM",2025-09-27,Shared in call,NaN,Interviewed,Waiting To Be Placed,Continue?
10,Pranav Kumar,pranav.in.kumar@gmail.com,pranav.kumar@yorkeducation.ca,Jing Zhang,"Jess Scott Sep 11, 2025 10:12 PM",2025-10-01,Shared in call,Done,Interviewed,In-training,Withdrawn
13,Alexander Artunduaga,alexander.artunduaga.1209@gmail.com,alexander.artunduaga@yorkeducation.ca,Jing Zhang,"Jess Scott Sep 12, 2025 9:36 AM",2025-09-26,Email sent,Done,Interviewed,In-training,Continue?
...,...,...,...,...,...,...,...,...,...,...,...
2228,Nafis Kamaree,nafisinfo2357@gmail.com,nafis.kamaree@yorkeducation.ca,Chelzy Evangelista,"Kevin Mar 12, 2026 7:40 PM",NaT,NaN,NaN,No Show,Waiting To Be Placed,NaN
2238,Ahmed Hossam Faisal Abdelbassit,medoaboelnasr065@gmail.com,ahmed.hossam.faisal.abdelbassit@yorkeducation.ca,NaN,"Jess Scott Sep 17, 2025 3:38 AM",NaT,NaN,NaN,No Show,Waiting To Be Placed,Withdrawn
2248,Fredrick Mulema,mulema1975@gmail.com,fredrick.mulema@yorkeducation.ca,NaN,"Jess Scott Mar 16, 2025 10:17 AM",NaT,NaN,NaN,No Show,Waiting To Be Placed,Withdrawn
2252,Hemangi Rane,hemangi.inbox@gmail.com,hemangi.rane@yorkeducation.ca,Jing Zhang,"Jess Scott Dec 11, 2025 4:44 AM",NaT,NaN,NaN,Interviewed,Waiting To Be Placed,NaN
2253,Bassirou Sagna,bassirou_sagna@yahoo.com,bassirou.sagna@yorkeducation.ca,Damon Carmen Tran,"Volunteer account Feb 5, 2026 5:45 AM",NaT,NaN,NaN,NaN,Waiting To Be Placed,Withdrawn

### Q5 Slack messages posted by VSP volunteers in March 2026

In [85]:
q5_merged = q3_merged.copy()

In [86]:
q5_merged

,Name_x,Creation log,Email Address,YRES Email,Contacted on Slack,Interview Status,Youth Advisor 3 - Winter 2026,Placement Status,Volunteer Status,Share account info,Name_y,Display name,Email,Account type,Account created (UTC),Days active,Messages posted,Messages posted in channels,Reactions added,Last active (UTC)
0,Mariam Ali,"U+ HR Account Sep 11, 2025 1:30 PM",mariam.ali@yorkeducation.ca,yafet.hailu@yorkeducation.ca,NaN,NaN,Bella He,Waiting To Be Placed,NaN,NaN,Yafet Hailu,Yafet Hailu,yafet.hailu@yorkeducation.ca,Member,2026-03-01,21.0,11.0,5.0,0.0,2026-03-30
1,Harvi Shah,"Jess Scott Sep 11, 2025 4:36 PM",harvishah2602@gmail.com,harvi.shah@yorkeducation.ca,Done,Interviewed,Tiffany Ye,In-training,Active,NaN,Harvishah,Harvishah,harvi.shah@yorkeducation.ca,Member,2025-10-19,0.0,0.0,0.0,0.0,2025-11-12
2,Dorsey Bangarh,"Jess Scott Sep 11, 2025 5:37 PM",dorseybangarh2004@gmail.com,dorsey.bangarh@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
3,Pushti Ladani,"Jess Scott Sep 11, 2025 7:26 PM",pushti-kantilal.ladani@mohawkcollege.ca,pushti.ladani@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
4,Purti Ladani,"Jess Scott Sep 11, 2025 7:29 PM",purti1002@gmail.com,purti.ladani@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249,Adamu Garba Bello,"Jess Scott Mar 20, 2025 10:07 AM",belloadamg@gmail.com,adamu.garbabello@yorkeducation.ca,NaN,Unbooked,NaN,Waiting To Be Placed,Withdrawn,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
2250,Melody Gramajo,"Jess Scott Oct 22, 2025 5:11 PM",celesmedready@gmail.com,melody.gramajo@yorkeducation.ca,Done,Interviewed,Chelzy Evangelista,Placed,Withdrawn,Shared in call,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
2251,Muzi Chen,"Jess Scott Sep 11, 2025 6:42 PM",muzi21@g.ucla.edu,muzi.chen@yorkeducation.ca,NaN,NaN,NaN,Waiting To Be Placed,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT
2252,Hemangi Rane,"Jess Scott Dec 11, 2025 4:44 AM",hemangi.inbox@gmail.com,hemangi.rane@yorkeducation.ca,NaN,Interviewed,Jing Zhang,Waiting To Be Placed,NaN,NaN,Hemangi Rane,Hemangi Rane,hemangi.rane@yorkeducation.ca,Invited Member,2025-12-12,0.0,0.0,0.0,0.0,NaT
2253,Bassirou Sagna,"Volunteer account Feb 5, 2026 5:45 AM",bassirou_sagna@yahoo.com,bassirou.sagna@yorkeducation.ca,NaN,NaN,Damon Carmen Tran,Waiting To Be Placed,Withdrawn,NaN,Bassirou Sagna,Bassirou Sagna,bassirou.sagna@yorkeducation.ca,Invited Member,2026-02-05,0.0,0.0,0.0,0.0,NaT

In [87]:
q5_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2254 entries, 0 to 2253
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Name_x                         2254 non-null   object
 1   Creation log                   2254 non-null   object
 2   Email Address                  2253 non-null   object
 3   YRES Email                     2254 non-null   object
 4   Contacted on Slack             941 non-null    object
 5   Interview Status               2068 non-null   object
 6   Youth Advisor 3 - Winter 2026  1858 non-null   object
 7   Placement Status               2254 non-null   object
 8   Volunteer Status               1314 non-null   object
 9   Share account info             984 non-null    object
 10  Name_y                         1761 non-null   object
 11  Display name                   1761 non-null   object
 12  Email                          1761 non-null   object
 13  Account type                   1761 non-null   object
 14  Account created (UTC)          1761 non-null   datetime64[ns]
 15  Days active                    1761 non-null   float64
 16  Messages posted                1761 non-null   float64
 17  Messages posted in channels    1761 non-null   float64
 18  Reactions added                1761 non-null   float64
 19  Last active (UTC)              1556 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(4), object(14)
memory usage: 352.3+ KB

In [88]:
march_start = pd.Timestamp('2026-03-01')

In [89]:
q5_answer = q5_merged[q5_merged['Last active (UTC)'] >= march_start].copy()

In [90]:
q5_answer = q5_answer[[
    'Name_x', 
    'YRES Email', 
    'Creation log',
    'Last active (UTC)', 
    'Messages posted', 
    'Messages posted in channels', 
    'Reactions added'
]]

In [91]:
q5_answer

,Name_x,YRES Email,Creation log,Last active (UTC),Messages posted,Messages posted in channels,Reactions added
0,Mariam Ali,yafet.hailu@yorkeducation.ca,"U+ HR Account Sep 11, 2025 1:30 PM",2026-03-30,11.0,5.0,0.0
5,Harjot Singh,harjot.singh@yorkeducation.ca,"Jess Scott Sep 11, 2025 8:52 PM",2026-03-27,4.0,1.0,0.0
8,Taranveer Arora,taranveer.arora@yorkeducation.ca,"Jess Scott Sep 11, 2025 9:32 PM",2026-03-10,0.0,0.0,0.0
25,Rabindranath Duran Pons,rabindranath.duran.pons@yorkeducation.ca,"Jess Scott Sep 14, 2025 2:13 PM",2026-03-30,0.0,0.0,0.0
26,Cindy Wu,cindy.wu@yorkeducation.ca,"Jess Scott Sep 14, 2025 3:04 PM",2026-03-01,0.0,0.0,0.0
...,...,...,...,...,...,...,...
2221,Mahdieh Sadat Sajadi,mahdieh.sajadi@yorkeducation.ca,"Kevin Feb 17, 2026 2:29 AM",2026-03-27,13.0,0.0,1.0
2222,Firoxi Bodhanwala,firoxi.bodhanwala@yorkeducation.ca,"Kevin Feb 23, 2026 8:10 AM",2026-03-30,16.0,6.0,7.0
2223,Manami Uraguchi,manami.uraguchi@yorkeducation.ca,"Kevin Mar 1, 2026 5:34 PM",2026-03-10,1.0,0.0,2.0
2227,Amel Yassin Mohamed,amel.mohamed@yorkeducation.ca,"Kevin Mar 12, 2026 1:38 AM",2026-03-27,2.0,0.0,2.0
2229,Maureen Ekweozoh,maureen.ekweozoh@yorkeducation.ca,"Kevin Mar 13, 2026 7:46 AM",2026-03-30,9.0,0.0,0.0